sudo: false
language: bash
os:
- linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - tree
  ssh_known_hosts:
    - www.amelvin.co.uk:4022
env:
  global:
    - SKETCH_LOCATION="$TRAVIS_BUILD_DIR"
install:
- set -e
- export CXX="g++-4.8" CC="gcc-4.8" GCOV="gcov-4.8"
- wget -O arduino.tar.xz https://www.arduino.cc/download.php?f=/arduino-nightly-linux64.tar.xz
- tar xf arduino.tar.xz
- mv arduino-nightly $HOME/arduino_ide
- cd $HOME/arduino_ide/hardware
- mkdir esp8266com
- cd esp8266com
- git clone https://github.com/esp8266/Arduino esp8266
- cd esp8266/tools
- python get.py
- export PATH="$HOME/arduino_ide:$HOME/arduino_ide/hardware/esp8266com/esp8266/tools/xtensa-lx106-elf/bin:$PATH"
- which arduino
- which xtensa-lx106-elf-size
- cd $TRAVIS_BUILD_DIR
- tree
- source travis/common.sh
- install_libraries
script:
- echo -e "travis_fold:end:sketch_test_env_prepare"
- echo -e "travis_fold:start:sketch_test"
- build_sketches $HOME/arduino_ide $SKETCH_LOCATION "-l $HOME/Arduino/libraries"
- echo -e "travis_fold:end:sketch_test"
- echo -e "travis_fold:start:size_report"
- cat size.log
- echo -e "travis_fold:end:size_report"
- export BINARY_FILE=$(find $TRAVIS_BUILD_DIR/build.tmp -iname "*.bin")
- echo $BINARY_FILE
before_install:
- openssl aes-256-cbc -K $encrypted_8a7607999119_key -iv $encrypted_8a7607999119_iv
  -in travisgit.enc -out /tmp/travis.key -d
- chmod 600 /tmp/travis.key
after_success:
  - mkdir /tmp/package
  - cp $BINARY_FILE "/tmp/package/firmware.bin"
  - cp -r "$SKETCH_LOCATION/data" "/tmp/package/"
  - ls /tmp/package/
deploy:
- provider: script
  skip_cleanup: true
  on:
    #repo: sticilface/ESPmanager
    all_branches: true
  script: /bin/sh travis/deploy.sh $BINARY_FILE latest
