sudo: false
language: bash
os:
- linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - tree
  ssh_known_hosts:
  - www.amelvin.co.uk:4022
env:
  global:
  - SKETCH_LOCATION="$TRAVIS_BUILD_DIR"
  - secure: xwPWHNhWemBD/aKlaswdPmdbLUd2dPNM4aUPa4z9lSmrHa09EEpfL/qu2bmMPcjqI2bxM0ZgUky7wDbxhVUajdJ+eveyF+y/ZYr1fjVHSn/D9PHfheD+1q3Fq+RtSY81/Vlpq3ZhBsVwo3D1ceFMI7Cff01k6xTy2TsVTV73CJ8koK/vDZnHgNY8fLnOedjAq5XUgFkcASAesFg7DHLrSiEZc7RoQ4eBpyDmRqAPHggk/4SVJsj7fSoV1DXspFPvS8mtii8lPwy1EH6CQ+twvZtgmAfngzBeMN3ZHMnwkzB/R5lXEbSKl/deFj3sfudgOo/9XOOJ3av13pahGDsATFPyAu6rj7FTQaddg2ezM7CL/2SMdXG2c+IwSG0WjfZXwXRJ6+WUVWzNIASixNu4MpdEQWtt9Mv2ujVdsiS3oVxqzQqwdwIGMkkiOprdvvIlopzU/bnrYRyImrwMpKicvNu/1RGZ32yM9QqBtl+sdBFJEmQyNXDVBqPWSaZY233WtI6q8SrLw73VyV/87K/wxXmo7Xk6BREVmcJJve1UOnlaI1B/CTEiyzllcRsINsMKdKbXj76IAhKcrgOL93ox4f9/fIKvQ9EMn0z5pKdovKKb0eknvvLozALGrBxiFPN2uwAT8YZ5Sd5/l0nD6g90O76NFY3PH8pdhjkptNPQY3s=
install:
- set -e
- export CXX="g++-4.8" CC="gcc-4.8" GCOV="gcov-4.8"
- wget -O arduino.tar.xz https://www.arduino.cc/download.php?f=/arduino-nightly-linux64.tar.xz
- tar xf arduino.tar.xz
- mv arduino-nightly $HOME/arduino_ide
- cd $HOME/arduino_ide/hardware
- mkdir esp8266com
- cd esp8266com
- git clone https://github.com/sticilface/arduino-esp8266 esp8266
- cd esp8266/tools
- python get.py
- export PATH="$HOME/arduino_ide:$HOME/arduino_ide/hardware/esp8266com/esp8266/tools/xtensa-lx106-elf/bin:$PATH"
- which arduino
- which xtensa-lx106-elf-size
- cd $TRAVIS_BUILD_DIR
- source $HOME/arduino_ide/hardware/esp8266com/esp8266/tests/common.sh
- install_libraries
script:
- echo -e "travis_fold:end:sketch_test_env_prepare"
- echo -e "travis_fold:start:sketch_test"
- build_sketches $HOME/arduino_ide $SKETCH_LOCATION "-l $HOME/Arduino/libraries"
- echo -e "travis_fold:end:sketch_test"
- echo -e "travis_fold:start:size_report"
- cat size.log
- echo -e "travis_fold:end:size_report"
- export BINARY_FILE=$(find $TRAVIS_BUILD_DIR/build.tmp -iname "*.bin")
- echo $BINARY_FILE
before_install:
- openssl aes-256-cbc -K $encrypted_8a7607999119_key -iv $encrypted_8a7607999119_iv
  -in travisgit.enc -out /tmp/travis.key -d
- chmod 600 /tmp/travis.key
after_success:
- mkdir /tmp/package
- cp $BINARY_FILE "/tmp/package/firmware.bin"
- cp -r "$SKETCH_LOCATION/data" "/tmp/package/"
- ls /tmp/package/
deploy:
- provider: script
  skip_cleanup: true
  on:
    all_branches: true
  script: /bin/sh travis/deploy.sh latest
