language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - ~/.platformio
env:
  matrix:
  - PLATFORMIO_CI_SRC="testfolder" 
install:
  - pip install -U platformio
  #- git clone https://github.com/esp8266/Arduino.git ./platformio/packages/framework-arduinoespressif
  # - git clone https://github.com/sticilface/arduino-esp8266 ./platformio/packages/framework-arduinoespressif
  - platformio lib install 64
  - mkdir /tmp/build
script:
  - platformio ci --board="esp12e" --build-dir="/tmp/build" --lib="." 
